# Generated by Django 6.0.1 on 2026-02-13 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cavaletes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CavaleteHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("STATUS_CHANGE", "Mudança de Status"),
                            ("START_AUDIT", "Início de Conferência"),
                            ("FINISH_AUDIT", "Fim de Conferência"),
                            ("ASSIGN", "Atribuição"),
                        ],
                        max_length=20,
                        verbose_name="ação",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "cavalete",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="cavaletes.cavalete",
                        verbose_name="cavalete",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de cavalete",
                "verbose_name_plural": "históricos de cavaletes",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SlotHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("STATUS_CHANGE", "Mudança de Status"),
                            ("START_AUDIT", "Início de Conferência"),
                            ("FINISH_AUDIT", "Fim de Conferência"),
                            ("ASSIGN", "Atribuição"),
                        ],
                        max_length=20,
                        verbose_name="ação",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "old_product_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "new_product_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("old_quantity", models.PositiveIntegerField(null=True)),
                ("new_quantity", models.PositiveIntegerField(null=True)),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="cavaletes.slot",
                        verbose_name="slot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de slot",
                "verbose_name_plural": "históricos de slots",
                "ordering": ["-timestamp"],
            },
        ),
    ]
