# Generated by Django 6.0.1 on 2026-02-13 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cavalete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="código"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nome/descrição"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponível"),
                            ("IN_PROGRESS", "Em conferência"),
                            ("COMPLETED", "Concluído"),
                            ("BLOCKED", "Bloqueado"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cavaletes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="conferente responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "cavalete",
                "verbose_name_plural": "cavaletes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("A", "Lado A"), ("B", "Lado B")],
                        max_length=1,
                        verbose_name="lado",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="número da posição"),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="código do produto",
                    ),
                ),
                (
                    "product_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="descrição do produto",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantidade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Aguardando"),
                            ("AUDITING", "Em conferência"),
                            ("COMPLETED", "Conferido"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cavalete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="cavaletes.cavalete",
                        verbose_name="cavalete",
                    ),
                ),
            ],
            options={
                "verbose_name": "slot",
                "verbose_name_plural": "slots",
                "ordering": ["cavalete", "side", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cavalete", "side", "number"),
                        name="unique_slot_position",
                    )
                ],
            },
        ),
    ]
