# Generated by Django 6.0.1 on 2026-02-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavaletes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavalete',
            name='name',
        ),
        migrations.AddField(
            model_name='cavalete',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Padrão'), ('PINE', 'Pinhal')], default='DEFAULT', max_length=20, verbose_name='tipo'),
        ),
    ]
